import pandas as pd
import numpy as np
import sys
import os
import argparse
from datetime import datetime
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
import warnings
warnings.filterwarnings('ignore')

# Add the shared directory to the path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'shared'))

from database import DatabaseManager

class RiskEstimationLogger:
    """Captures print statements and saves them to markdown and HTML files."""
    
    def __init__(self):
        self.output_dir = os.path.join(os.path.dirname(__file__), '..', 'risk_estimate_outputs')
        os.makedirs(self.output_dir, exist_ok=True)
        
        self.timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.session_id = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        self.md_file = os.path.join(self.output_dir, "risk_estimate_session.md")
        self.html_file = os.path.join(self.output_dir, "risk_estimate_session.html")
        self.txt_file = os.path.join(self.output_dir, "risk_estimate_session.txt")
        
        # Initialize markdown and text files
        self._initialize_markdown()
        self._initialize_text()
        
        # Store original print function
        self.original_print = print
        
        # Replace built-in print with our logger
        import builtins
        builtins.print = self.log_print
    
    def _initialize_markdown(self):
        """Initialize the markdown file with header (overwrite existing)."""
        with open(self.md_file, 'w', encoding='utf-8') as f:
            f.write(f"""# Risk Estimation Session Report

**Date:** {self.session_id}  
**Session ID:** {self.timestamp}  
**Generated by:** Delinquency Data Management System (DDMS)

---

""")
    
    def _initialize_text(self):
        """Initialize the text file with header (overwrite existing)."""
        with open(self.txt_file, 'w', encoding='utf-8') as f:
            f.write(f"""Risk Estimation Session Report

Date: {self.session_id}
Session ID: {self.timestamp}
Generated by: Delinquency Data Management System (DDMS)

{'-' * 50}

""")

    def log_print(self, *args, sep=' ', end='\n', file=None, flush=False):
        """Custom print function that logs to console, markdown and text files."""
        # Call original print for console output
        self.original_print(*args, sep=sep, end=end, file=file, flush=flush)
        
        # Format the message
        message = sep.join(str(arg) for arg in args) + end
        
        # Append to text file (simple, unformatted)
        with open(self.txt_file, 'a', encoding='utf-8') as f:
            f.write(message)
        
        # Append to markdown file
        with open(self.md_file, 'a', encoding='utf-8') as f:
            message_stripped = message.strip()
            
            # Skip empty messages
            if not message_stripped:
                f.write(message)
                return
            
            # Format for markdown based on content patterns
            if message_stripped.startswith('='):
                # Header lines with equals signs
                header_text = message_stripped.replace('=', '').strip()
                if header_text:  # Only create header if there's actual content
                    f.write(f"\n## {header_text}\n\n")
                else:
                    f.write("\n---\n\n")  # Use horizontal rule for separator lines
                    
            elif message_stripped.startswith('PERFORMANCE METRICS'):
                # Performance metrics header
                f.write(f"\n### {message_stripped}\n\n")
                
            elif message_stripped.startswith('-') and len(set(message_stripped)) <= 2:
                # Lines that are just dashes (separators) - convert to horizontal rules
                f.write("\n---\n\n")
                
            elif any(title in message_stripped for title in [
                'Top 20 Most Influential Features',
                'Feature Importance by Data',
                'BEST MODEL SUMMARY',
                'Starting Comprehensive',
                'Delinquency analysis complete',
                'COMPREHENSIVE DELINQUENCY ANALYSIS REPORT'
            ]):
                # Important section headers
                f.write(f"\n## {message_stripped.rstrip(':')}\n\n")
                
            elif any(status in message_stripped for status in [
                'Feature engineering complete',
                'ML dataset prepared'
            ]):
                # Status messages - make bold and ensure separate lines
                f.write(f"**{message_stripped}**\n\n")
                
            elif message_stripped.endswith(':') and any(section in message_stripped for section in [
                'Dataset Overview', 'Model Performance Summary', 'Risk Score Distribution',
                'Risk Score Validation', 'Sample', 'Risk Factors for Delinquency'
            ]):
                # Report subsection headers
                f.write(f"\n### {message_stripped.rstrip(':')}\n\n")
                
            elif message_stripped.startswith('- ') or (
                message_stripped.startswith(' ') and message_stripped.lstrip().startswith('-')
            ):
                # List items (bullet points)
                clean_item = message_stripped.lstrip()
                f.write(f"{clean_item}\n")
                
            elif any(table_indicator in message_stripped for table_indicator in [
                'Model', '----', 'Random Forest', 'Gradient Boosting', 
                'Logistic Regression', 'SVC'
            ]) and ('----' in message_stripped or 
                   any(model in message_stripped for model in ['Random Forest', 'Gradient Boosting', 'Logistic Regression', 'SVC'])):
                # Table content (model comparison tables) - format as code block for alignment  
                if '----' in message_stripped:
                    f.write(f"\n```\n{message_stripped}\n")
                elif any(model in message_stripped for model in ['Random Forest', 'Gradient Boosting', 'Logistic Regression', 'SVC']):
                    f.write(f"{message_stripped}\n")
                    if 'SVC' in message_stripped:  # Last model in table
                        f.write("```\n\n")
                else:
                    f.write(f"{message_stripped}\n")
                
            elif message.startswith('  ') and not message.startswith('   '):
                # Indented content (2 spaces) - check for performance metrics
                clean_text = message.strip()
                # Remove bold formatting for processing
                clean_text_no_bold = clean_text.replace('**', '')
                
                # Always check if this could be a performance metric, regardless of table state
                if (':' in clean_text_no_bold and any(metric in clean_text_no_bold.lower() for metric in [
                    'accuracy', 'precision', 'recall', 'f1', 'auc'])):
                    
                    # If we're in a performance table, format as table row
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        parts = clean_text_no_bold.split(':', 1)
                        if len(parts) == 2:
                            metric = parts[0].strip()
                            value = parts[1].strip()
                            f.write(f"| {metric} | {value} |\n")
                        else:
                            # Could not split properly, write as is
                            f.write(f"  {message}")
                    
                    # If we're in a best model table, format as table row
                    elif hasattr(self, '_in_best_model_table') and self._in_best_model_table:
                        parts = clean_text_no_bold.split(':', 1)
                        if len(parts) == 2:
                            metric = parts[0].strip()
                            value = parts[1].strip()
                            # Make metric names bold for better formatting
                            f.write(f"| **{metric}** | {value} |\n")
                        else:
                            # Could not split properly, write as is
                            f.write(f"  {message}")
                    
                    else:
                        # Outside performance/best model table, format as bullet
                        f.write(f"- {clean_text}\n")
                
                # Handle other CV metrics  
                elif ':' in clean_text and 'cv' in clean_text.lower():
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        # End table if we have CV metrics outside the table context
                        f.write(f"\n")
                        self._in_performance_table = False
                    if hasattr(self, '_in_best_model_table') and self._in_best_model_table:
                        # End best model table if we have CV metrics outside the table context
                        f.write(f"\n")
                        self._in_best_model_table = False
                    f.write(f"- {clean_text}\n")
                else:
                    # End performance table if we're in one and this doesn't look like a metric
                    if hasattr(self, '_in_performance_table') and self._in_performance_table and not any(metric in clean_text_no_bold.lower() for metric in ['accuracy', 'precision', 'recall', 'f1', 'auc']):
                        f.write(f"\n")
                        self._in_performance_table = False
                    # End best model table if we're in one and this doesn't look like a metric
                    if hasattr(self, '_in_best_model_table') and self._in_best_model_table and not any(metric in clean_text_no_bold.lower() for metric in ['accuracy', 'precision', 'recall', 'f1', 'auc']):
                        f.write(f"\n")
                        self._in_best_model_table = False
                    # Regular indented content
                    f.write(f"  {message}\n")
                    
            elif message_stripped.startswith('    '):
                # Deeply indented content (4+ spaces) - check for classification reports
                clean_text = message_stripped.strip()
                
                # Check if we're in a classification report and this is report content
                if (hasattr(self, '_in_classification_report') and self._in_classification_report and 
                    (('precision' in clean_text.lower() and 'recall' in clean_text.lower() and 'f1' in clean_text.lower()) or
                     any(label in clean_text.lower() for label in ['macro avg', 'weighted avg', 'accuracy', 'support']) or
                     # Check if it looks like a classification report row
                     (len(clean_text.split()) >= 3 and any(char.replace('.', '').replace(' ', '').isdigit() for char in clean_text.split())) or
                     # Empty lines or formatting lines
                     clean_text == '' or all(c in ' -' for c in clean_text) or
                     # Class labels with numbers (like "0" and "1" classes)
                     (len(clean_text.split()) >= 4 and clean_text.split()[0].isdigit()))):
                    # Add to classification report code block
                    f.write(f"{clean_text}\n")
                
                # Check if it starts a confusion matrix
                elif clean_text.startswith('[[') or (clean_text.startswith('[') and ']' in clean_text):
                    if hasattr(self, '_in_classification_report') and self._in_classification_report:
                        # End the classification report code block, add confusion matrix header
                        f.write("```\n\n")
                        f.write("#### Confusion Matrix:\n\n")
                        f.write(f"{clean_text}\n")
                        
                # Check if it's a best model result that should be highlighted
                elif 'best performing model' in clean_text.lower() or 'best model auc score' in clean_text.lower():
                    # End any open blocks
                    if hasattr(self, '_in_classification_report') and self._in_classification_report:
                        f.write("```\n\n")
                        self._in_classification_report = False
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        f.write(f"\n")
                        self._in_performance_table = False
                        
                    # Create prominent best model section
                    f.write(f"\n## 🏆 Best Model Results\n\n")
                    f.write(f"**{clean_text}**\n\n")
                    
                else:
                    # End classification report if we were in one and this doesn't look like report content
                    if hasattr(self, '_in_classification_report') and self._in_classification_report:
                        f.write("```\n\n")
                        self._in_classification_report = False
                        
                    # End performance table if we were in one
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        f.write(f"\n")
                        self._in_performance_table = False
                        
                    # Regular deeply indented content - format as code block
                    f.write(f"    {message}")
                
            elif message_stripped.startswith('Training '):
                # Algorithm training headers - make them blue and on separate lines
                algo_name = message_stripped.replace('Training ', '').rstrip('.')
                f.write(f"\n<span style='color: blue; font-weight: bold;'>### Training {algo_name}</span>\n\n")
            
            # Handle unformatted database messages that appear as plain text
            elif (message_stripped in ['delinquency_risk column already exists', 'Updated 1000 risk scores in loan_info table'] or
                  ('Updated' in message_stripped and 'risk scores' in message_stripped and 'table' in message_stripped)):
                f.write(f"*{message_stripped}*\n\n")
                
            elif ':' in message_stripped and not message_stripped.startswith('\n'):
                # Key-value pairs - but be more selective
                
                # Check for performance section headers
                if message_stripped == 'Test Set Performance:':
                    # End any active tables first
                    if hasattr(self, '_in_best_model_table') and self._in_best_model_table:
                        f.write(f"\n")
                        self._in_best_model_table = False
                    f.write(f"\n### Test Set Performance\n\n")
                    f.write("| Metric | Value |\n")
                    f.write("|--------|-------|\n")
                    self._in_performance_table = True
                    
                elif message_stripped.startswith('Cross-Validation Performance'):
                    # End previous table if active
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        f.write(f"\n")
                        self._in_performance_table = False
                    if hasattr(self, '_in_best_model_table') and self._in_best_model_table:
                        f.write(f"\n")
                        self._in_best_model_table = False
                    f.write(f"\n### {message_stripped}\n\n") 
                    f.write("| Metric | Value |\n")
                    f.write("|--------|-------|\n")
                    self._in_performance_table = True
                    
                # Check for confusion matrix header
                elif message_stripped == 'Confusion Matrix:':
                    # End performance table if active
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        f.write(f"\n")
                        self._in_performance_table = False
                    if hasattr(self, '_in_best_model_table') and self._in_best_model_table:
                        f.write(f"\n")
                        self._in_best_model_table = False
                    # Start confusion matrix code block without header - just the code block
                    f.write("```\n")
                    self._in_classification_report = True
                
                # Check for Best Performing Model header - start table format
                elif message_stripped.startswith('Best Performing Model:'):
                    # End any active tables first
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        f.write(f"\n")
                        self._in_performance_table = False
                    if hasattr(self, '_in_classification_report') and self._in_classification_report:
                        f.write(f"```\n\n")
                        self._in_classification_report = False
                    
                    # Extract model name from the message
                    model_name = message_stripped.replace('Best Performing Model:', '').strip()
                    f.write(f"\n### Best Performing Model: {model_name}\n\n")
                    f.write("| Metric | Value |\n")
                    f.write("|--------|-------|\n")
                    self._in_best_model_table = True
                
                elif any(pattern in message_stripped.lower() for pattern in [
                    'dataset shape', 'algorithm', 'risk levels', 'loaded', 'records for analysis'
                ]):
                    f.write(f"**{message_stripped}**\n\n")
                elif message_stripped.startswith('Features available:'):
                    # Special handling for features available - only make the label bold
                    features_text = message_stripped.replace('Features available:', '').strip()
                    f.write(f"**Features available:** {features_text}\n\n")
                elif message_stripped.startswith('Feature list:'):
                    # Special handling for feature list - only make the label bold  
                    features_text = message_stripped.replace('Feature list:', '').strip()
                    f.write(f"**Feature list:** {features_text}\n\n")
                elif 'Feature engineering complete' in message_stripped or 'ML dataset prepared' in message_stripped:
                    # Make these status messages bold and ensure they're on separate lines
                    if 'Feature engineering complete' in message_stripped and 'ML dataset prepared' in message_stripped:
                        # Split the combined message into separate lines
                        parts = message_stripped.split('ML dataset prepared')
                        f.write(f"**{parts[0].strip()}**\n\n")
                        f.write(f"**ML dataset prepared{parts[1].strip()}**\n\n")
                    else:
                        f.write(f"**{message_stripped}**\n\n")
                # Handle database status messages and risk statistics
                elif any(db_msg in message_stripped for db_msg in [
                    'delinquency_risk column already exists', 
                    'Updated 1000 risk scores in loan_info table',
                    'Updated', 'risk scores in', 'table'
                ]) and len(message_stripped) < 200:  # Make sure it's a short database message
                    # Format database status messages as informational notes
                    f.write(f"*{message_stripped}*\n\n")
                elif ':' in message_stripped and 'Risk score statistics' in message_stripped:
                    # Skip the duplicate "Risk score statistics:" header completely
                    pass
                elif (message_stripped.count(':') == 1 and len(message_stripped) < 100 and
                      not any(metric in message_stripped.lower() for metric in ['accuracy', 'precision', 'recall', 'f1', 'auc'])):
                    # Short key-value pairs (but not performance metrics)
                    f.write(f"**{message_stripped}**\n")
                else:
                    # Long content with colons - treat as regular text
                    f.write(message)
                    
            elif message_stripped and message_stripped[0].isdigit() and ('. ' in message_stripped or ') ' in message_stripped):
                # Numbered list items
                f.write(f"{message_stripped}\n")
                
            elif message_stripped.startswith('Payer ') and 'Risk Level' in message_stripped:
                # Sample borrower entries
                f.write(f"- {message_stripped}\n")
                
            elif message_stripped and any(indicator in message_stripped for indicator in [
                'Actual Delinquency Rate:', 'Borrowers in Level:', 'Total borrowers analyzed:',
                'Delinquent borrowers:', 'Overall delinquency rate:', 'Low Risk (', 'Medium Risk (',
                'High Risk (', 'Risk Score Distribution Summary', 'Algorithm:', 'risk score statistics'
            ]):
                # Statistical information and risk statistics - format as bullet points or sections
                if 'Risk Score Distribution Summary' in message_stripped:
                    f.write(f"\n### {message_stripped}\n\n")
                    # Initialize or reset risk stats tracking for this section
                    self._risk_stats_shown = set()
                elif message_stripped.startswith('Risk score statistics:') or 'risk score statistics' in message_stripped.lower():
                    # Skip this duplicate header since we already have the distribution above
                    pass
                elif message_stripped.startswith('Algorithm:') and 'random_forest' in message_stripped:
                    f.write(f"**{message_stripped}**\n\n")
                elif any(risk_level in message_stripped for risk_level in ['Low Risk (', 'Medium Risk (', 'High Risk (']):
                    # Format risk level statistics as bullet points, avoiding duplication
                    if not hasattr(self, '_risk_stats_shown'):
                        self._risk_stats_shown = set()
                    
                    # Create a clean identifier for this risk statistic to avoid duplication
                    risk_clean = message_stripped.split(':')[0].strip() if ':' in message_stripped else message_stripped.split('(')[0].strip()
                    
                    if risk_clean not in self._risk_stats_shown:
                        self._risk_stats_shown.add(risk_clean)
                        f.write(f"- {message_stripped}\n")
                elif message_stripped.startswith('    '):  # Other indented stats
                    clean_text = message_stripped.strip()
                    f.write(f"  - {clean_text}\n")
                else:
                    f.write(f"- {message_stripped}\n")
            else:
                # Regular content - check if it's a performance metric that wasn't caught elsewhere
                if (message_stripped.startswith(' ') and 
                    ':' in message_stripped and 
                    any(metric in message_stripped.lower() for metric in ['accuracy', 'precision', 'recall', 'f1', 'auc'])):
                    
                    clean_text = message_stripped.strip().replace('**', '')
                    
                    # If we're in a performance table, format as table row
                    if hasattr(self, '_in_performance_table') and self._in_performance_table:
                        parts = clean_text.split(':', 1)
                        if len(parts) == 2:
                            metric = parts[0].strip()
                            value = parts[1].strip()
                            f.write(f"| {metric} | {value} |\n")
                        else:
                            # Fall back to regular formatting
                            f.write(message)
                    else:
                        # Outside performance table, format as bullet
                        f.write(f"- {clean_text}\n")
                else:
                    # Check if this is confusion matrix data
                    if ('[' in message_stripped and ']' in message_stripped and 
                        (message_stripped.startswith('[[') or message_stripped.startswith('[')) and
                        hasattr(self, '_in_classification_report') and self._in_classification_report):
                        # End classification report, add confusion matrix header
                        f.write("```\n\n")
                        f.write("#### Confusion Matrix:\n\n")
                        # Don't set _in_classification_report = False yet, let the next matrix line continue
                        f.write(f"{message_stripped}\n")
                    else:
                        # Regular content
                        f.write(message)
    
    def finalize_session(self):
        """Finalize the session and convert markdown to HTML."""
        # Close any open blocks before session footer
        with open(self.md_file, 'a', encoding='utf-8') as f:
            # Close classification report if still open
            if hasattr(self, '_in_classification_report') and self._in_classification_report:
                f.write("```\n\n")
                self._in_classification_report = False
            
            # Close performance table if still open
            if hasattr(self, '_in_performance_table') and self._in_performance_table:
                f.write(f"\n")
                self._in_performance_table = False
                
            # Add session footer
            f.write(f"\n---\n\n*Session completed at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
        
        # Reset tracking variables for next session
        if hasattr(self, '_risk_stats_shown'):
            delattr(self, '_risk_stats_shown')
            
        # Convert markdown to HTML
        self._convert_to_html()
        
        # Restore original print
        import builtins
        builtins.print = self.original_print
        
        return self.md_file, self.html_file, self.txt_file
    
    def _convert_to_html(self):
        """Convert markdown file to HTML."""
        try:
            import markdown
            
            # Read markdown content
            with open(self.md_file, 'r', encoding='utf-8') as f:
                md_content = f.read()
            
            # Convert to HTML
            html_content = markdown.markdown(md_content, extensions=['tables', 'codehilite'])
            
            # Wrap in complete HTML document
            full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Risk Estimation Session Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; }}
        h1, h2, h3 {{ color: #2c3e50; }}
        h1 {{ border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ border-bottom: 1px solid #bdc3c7; padding-bottom: 5px; }}
        code {{ background-color: #f8f9fa; padding: 2px 4px; border-radius: 3px; }}
        pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; overflow-x: auto; }}
        .timestamp {{ color: #7f8c8d; font-style: italic; }}
        strong {{ color: #2c3e50; }}
    </style>
</head>
<body>
    {html_content}
</body>
</html>"""
            
            # Save HTML file
            with open(self.html_file, 'w', encoding='utf-8') as f:
                f.write(full_html)
                
        except ImportError:
            # Fallback: create simple HTML without markdown parsing
            with open(self.md_file, 'r', encoding='utf-8') as f:
                md_content = f.read()
            
            # Simple HTML conversion
            html_content = md_content.replace('\n', '<br>\n').replace('**', '<strong>').replace('**', '</strong>')
            
            full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Risk Estimation Session Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 1200px; margin: 0 auto; padding: 20px; }}
        pre {{ background-color: #f8f9fa; padding: 15px; border-radius: 5px; }}
    </style>
</head>
<body>
    <pre>{html_content}</pre>
</body>
</html>"""
            
            with open(self.html_file, 'w', encoding='utf-8') as f:
                f.write(full_html)

# Initialize the loggerUser Profile Features:
_session_logger = None

def init_session_logging():
    """Initialize session logging."""
    global _session_logger
    _session_logger = RiskEstimationLogger()
    return _session_logger

def finalize_session_logging():
    """Finalize session logging and return file paths."""
    global _session_logger
    if _session_logger:
        return _session_logger.finalize_session()
    return None, None, None

def load_comprehensive_dataset(db_path=None):
    """
    Load and merge all tables for comprehensive delinquency analysis using centralized database methods.
    
    Args:
        db_path: Optional path to the database file. If None, uses default location.
        
    Returns a DataFrame with all relevant features and target variable.
    """
    db_manager = DatabaseManager(db_path) if db_path else DatabaseManager()
    
    # Get comprehensive data using centralized method
    data = db_manager.get_delinquency_analysis_data()
    
    # Convert to DataFrame
    df = pd.DataFrame(data)
    
    if df.empty:
        print("Error: No data found in database")
        return pd.DataFrame()
    
    print(f"Loaded {len(df):,} records for analysis")
    print(f"Dataset shape: {df.shape}")
    print(f"Features available: {df.columns.tolist()}")
    
    return df

def engineer_features(df):
    """
    Engineer additional features for better delinquency prediction.
    """
    # Date-based features
    df['origination_date'] = pd.to_datetime(df['origination_date'])
    df['disbursement_date'] = pd.to_datetime(df['disbursement_date'])
    df['maturity_date'] = pd.to_datetime(df['maturity_date'])
    
    current_date = pd.Timestamp.now()
    
    # Time-based features
    df['loan_age_days'] = (current_date - df['origination_date']).dt.days
    df['days_since_disbursement'] = (current_date - df['disbursement_date']).dt.days
    df['days_to_maturity'] = (df['maturity_date'] - current_date).dt.days
    df['loan_progress_pct'] = df['loan_age_days'] / (df['loan_term_years'] * 365)
    
    # Financial ratios
    df['debt_to_income_ratio'] = df['loan_amount'] / np.maximum(df['annual_income_cad'], 1)
    df['payment_to_income_ratio'] = (df['monthly_payment'] * 12) / np.maximum(df['annual_income_cad'], 1)
    df['education_roi'] = df['average_starting_salary'] / np.maximum(df['typical_tuition_cad'], 1)
    df['loan_to_education_value_ratio'] = df['loan_amount'] / df['education_value']
    
    # Payment behavior features
    df['delinquency_rate'] = df['missed_payments'] / np.maximum(df['total_payments_made'], 1)
    df['payment_consistency'] = df['on_time_payments'] / np.maximum(df['total_payments_made'], 1)
    # Note: total_late_fees not available, using missed_payments as proxy for late fees
    df['avg_late_fee_per_payment'] = df['missed_payments'] / np.maximum(df['total_payments_made'], 1)
    
    # Risk category features
    df['high_ltv_risk'] = (df['ltv_ratio'] > 80).astype(int)
    df['low_income_risk'] = (df['annual_income_cad'] < 40000).astype(int)
    df['young_borrower_risk'] = (df['age'] < 26).astype(int)
    df['long_term_loan_risk'] = (df['loan_term_years'] > 15).astype(int)
    df['high_difficulty_program'] = (df['program_difficulty'] == 3).astype(int)
    
    # Employment market features
    df['low_employment_rate'] = (df['employment_rate'] < 80).astype(int)
    df['poor_job_outlook'] = (df['job_market_outlook'] == 'Challenging').astype(int)
    
    print(f"Feature engineering complete. Dataset now has {len(df.columns)} features")
    
    return df

def prepare_ml_features(df):
    """
    Prepare features for machine learning by encoding categorical variables.
    """
    # Create a copy for ML processing
    ml_df = df.copy()
    
    # Categorical features to encode
    categorical_features = [
        'employment_status', 'marital_status', 'province', 'loan_type', 
        'institution_province', 'lender', 'program_type', 'field_of_study',
        'accreditation_body', 'institution_type', 'university_name', 
        'requires_licensing', 'job_market_outlook', 'loan_status'
    ]
    
    # Label encoding for categorical features
    label_encoders = {}
    for feature in categorical_features:
        if feature in ml_df.columns:
            le = LabelEncoder()
            ml_df[feature + '_encoded'] = le.fit_transform(ml_df[feature].fillna('Unknown'))
            label_encoders[feature] = le
    
    # Select numerical and encoded features for ML
    feature_columns = [col for col in ml_df.columns if 
                      (ml_df[col].dtype in ['int64', 'float64'] and 
                       col not in ['payer_id', 'is_delinquent']) or 
                      col.endswith('_encoded')]
    
    # Handle missing values
    ml_df[feature_columns] = ml_df[feature_columns].fillna(ml_df[feature_columns].mean())
    
    # Remove infinite values
    ml_df[feature_columns] = ml_df[feature_columns].replace([np.inf, -np.inf], np.nan)
    ml_df[feature_columns] = ml_df[feature_columns].fillna(ml_df[feature_columns].mean())
    
    X = ml_df[feature_columns]
    y = ml_df['is_delinquent']
    
    print(f"ML dataset prepared with {X.shape[1]} features for {X.shape[0]} samples")
    print(f"Feature list: {X.columns.tolist()}")
    
    return X, y, feature_columns, label_encoders

def train_delinquency_models(X, y):
    """
    Train multiple ML models and select the best performer.
    """
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    
    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Define models
    models = {
        'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42),
        'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, max_depth=6, random_state=42),
        'Logistic Regression': LogisticRegression(random_state=42, max_iter=1000),
        'SVC': SVC(kernel='rbf', probability=True, random_state=42),
        # Temporarily commenting out KNN due to NumPy compatibility issue
        # 'KNN': KNeighborsClassifier(n_neighbors=5)
    }
    
    # Train and evaluate models
    model_results = {}
    
    for name, model in models.items():
        print(f"\nTraining {name}...")
        
        if name == 'Logistic Regression':
            model.fit(X_train_scaled, y_train)
            y_pred = model.predict(X_test_scaled)
            y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]
        else:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            y_pred_proba = model.predict_proba(X_test)[:, 1]
        
        # Calculate comprehensive metrics
        from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
        
        auc_score = roc_auc_score(y_test, y_pred_proba)
        accuracy = accuracy_score(y_test, y_pred)
        precision = precision_score(y_test, y_pred, average='weighted')
        recall = recall_score(y_test, y_pred, average='weighted')
        f1 = f1_score(y_test, y_pred, average='weighted')
        
        cv_scores = cross_val_score(model, X_train_scaled if name == 'Logistic Regression' else X_train, 
                                   y_train, cv=5, scoring='roc_auc')
        
        # Calculate additional CV scores for different metrics
        cv_accuracy = cross_val_score(model, X_train_scaled if name == 'Logistic Regression' else X_train, 
                                     y_train, cv=5, scoring='accuracy')
        cv_precision = cross_val_score(model, X_train_scaled if name == 'Logistic Regression' else X_train, 
                                      y_train, cv=5, scoring='precision_weighted')
        cv_recall = cross_val_score(model, X_train_scaled if name == 'Logistic Regression' else X_train, 
                                   y_train, cv=5, scoring='recall_weighted')
        cv_f1 = cross_val_score(model, X_train_scaled if name == 'Logistic Regression' else X_train, 
                               y_train, cv=5, scoring='f1_weighted')
        
        model_results[name] = {
            'model': model,
            'auc_score': auc_score,
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'cv_auc_mean': cv_scores.mean(),
            'cv_auc_std': cv_scores.std(),
            'cv_accuracy_mean': cv_accuracy.mean(),
            'cv_accuracy_std': cv_accuracy.std(),
            'cv_precision_mean': cv_precision.mean(),
            'cv_precision_std': cv_precision.std(),
            'cv_recall_mean': cv_recall.mean(),
            'cv_recall_std': cv_recall.std(),
            'cv_f1_mean': cv_f1.mean(),
            'cv_f1_std': cv_f1.std(),
            'predictions': y_pred_proba
        }
        
        # Display comprehensive performance metrics
        print(f"\n{'='*60}")
        print(f"PERFORMANCE METRICS - {name}")
        print(f"{'='*60}")
        print(f"Test Set Performance:")
        print(f"  Accuracy:  {accuracy:.4f}")
        print(f"  Precision: {precision:.4f}")
        print(f"  Recall:    {recall:.4f}")
        print(f"  F1-Score:  {f1:.4f}")
        print(f"  AUC Score: {auc_score:.4f}")
        
        print(f"\nCross-Validation Performance (5-fold):")
        print(f"  Accuracy:  {cv_accuracy.mean():.4f} (+/- {cv_accuracy.std() * 2:.4f})")
        print(f"  Precision: {cv_precision.mean():.4f} (+/- {cv_precision.std() * 2:.4f})")
        print(f"  Recall:    {cv_recall.mean():.4f} (+/- {cv_recall.std() * 2:.4f})")
        print(f"  F1-Score:  {cv_f1.mean():.4f} (+/- {cv_f1.std() * 2:.4f})")
        print(f"  AUC:       {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")
        
        print(f"\nConfusion Matrix:")
        print(confusion_matrix(y_test, y_pred))
    
    # Select best model based on AUC score
    best_model_name = max(model_results.keys(), key=lambda x: model_results[x]['auc_score'])
    best_model = model_results[best_model_name]['model']
    
    print(f"\nBest performing model: {best_model_name}")
    print(f"Best model AUC Score: {model_results[best_model_name]['auc_score']:.4f}")
    
    return best_model, model_results, scaler
def train_single_algorithm(X, y, algorithm):
    """
    Train only the specified ML algorithm instead of all models.
    
    Args:
        X: Feature matrix
        y: Target labels
        algorithm: The specific algorithm to train
    
    Returns:
        Tuple of (model, model_results, scaler, model_name)
    """
    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)
    
    # Scale features
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    
    # Algorithm mapping
    algorithm_map = {
        'random_forest': ('Random Forest', RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)),
        'gradient_boosting': ('Gradient Boosting', GradientBoostingClassifier(n_estimators=100, max_depth=6, random_state=42)),
        'logistic_regression': ('Logistic Regression', LogisticRegression(random_state=42, max_iter=1000)),
        'neural_network': ('Neural Network', MLPClassifier(hidden_layer_sizes=(100, 50), random_state=42, max_iter=500)),
        'svm': ('SVM', SVC(kernel='rbf', probability=True, random_state=42)),
        'knn': ('KNN', KNeighborsClassifier(n_neighbors=5))
    }
    
    if algorithm not in algorithm_map:
        raise ValueError(f"Unknown algorithm: {algorithm}")
    
    model_name, model = algorithm_map[algorithm]
    
    print(f"\nTraining {model_name}...")
    
    # Train the specific model with special handling for KNN NumPy compatibility issue
    if algorithm == 'logistic_regression':
        model.fit(X_train_scaled, y_train)
        y_pred = model.predict(X_test_scaled)
        y_pred_proba = model.predict_proba(X_test_scaled)[:, 1]
    elif algorithm == 'knn':
        # Special handling for KNN to fix NumPy compatibility issues
        # Ensure arrays are properly formatted and contiguous
        X_train_knn = np.ascontiguousarray(X_train.astype(np.float64))
        X_test_knn = np.ascontiguousarray(X_test.astype(np.float64))
        y_train_knn = np.ascontiguousarray(y_train.astype(np.int32))
        
        model.fit(X_train_knn, y_train_knn)
        y_pred = model.predict(X_test_knn)
        
        # For KNN probability prediction, we need to be careful about array formatting
        X_test_knn_proba = np.ascontiguousarray(X_test_knn.astype(np.float64))
        y_pred_proba = model.predict_proba(X_test_knn_proba)[:, 1]
    else:
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        y_pred_proba = model.predict_proba(X_test)[:, 1]
    
    # Calculate comprehensive metrics
    from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
    
    auc_score = roc_auc_score(y_test, y_pred_proba) if len(set(y_test)) > 1 else 0.0
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    
    cv_scores = cross_val_score(model, X_train_scaled if algorithm == 'logistic_regression' else X_train, y_train, cv=5, scoring='roc_auc')
    
    # Calculate additional CV scores for different metrics
    # Special handling for KNN to avoid NaN values
    try:
        if algorithm == 'knn':
            # For KNN, use properly formatted arrays for cross-validation
            X_cv = np.ascontiguousarray(X_train.astype(np.float64))
            y_cv = np.ascontiguousarray(y_train.astype(np.int32))
            cv_accuracy = cross_val_score(model, X_cv, y_cv, cv=5, scoring='accuracy')
            cv_precision = cross_val_score(model, X_cv, y_cv, cv=5, scoring='precision_weighted')
            cv_recall = cross_val_score(model, X_cv, y_cv, cv=5, scoring='recall_weighted')
            cv_f1 = cross_val_score(model, X_cv, y_cv, cv=5, scoring='f1_weighted')
        elif algorithm == 'logistic_regression':
            cv_accuracy = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='accuracy')
            cv_precision = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='precision_weighted')
            cv_recall = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='recall_weighted')
            cv_f1 = cross_val_score(model, X_train_scaled, y_train, cv=5, scoring='f1_weighted')
        else:
            cv_accuracy = cross_val_score(model, X_train, y_train, cv=5, scoring='accuracy')
            cv_precision = cross_val_score(model, X_train, y_train, cv=5, scoring='precision_weighted')
            cv_recall = cross_val_score(model, X_train, y_train, cv=5, scoring='recall_weighted')
            cv_f1 = cross_val_score(model, X_train, y_train, cv=5, scoring='f1_weighted')
    except Exception as cv_error:
        print(f"Cross-validation error for {algorithm}: {cv_error}")
        # Fallback to single values if CV fails
        cv_accuracy = np.array([accuracy])
        cv_precision = np.array([precision])
        cv_recall = np.array([recall])
        cv_f1 = np.array([f1])
    
    # Display comprehensive performance metrics
    print(f"\n{'='*60}")
    print(f"PERFORMANCE METRICS - {model_name}")
    print(f"{'='*60}")
    print(f"Test Set Performance:")
    print(f"  Accuracy:  {accuracy:.4f}")
    print(f"  Precision: {precision:.4f}")
    print(f"  Recall:    {recall:.4f}")
    print(f"  F1-Score:  {f1:.4f}")
    print(f"  AUC Score: {auc_score:.4f}")
    
    print(f"\nCross-Validation Performance (5-fold):")
    print(f"  Accuracy:  {cv_accuracy.mean():.4f} (+/- {cv_accuracy.std() * 2:.4f})")
    print(f"  Precision: {cv_precision.mean():.4f} (+/- {cv_precision.std() * 2:.4f})")
    print(f"  Recall:    {cv_recall.mean():.4f} (+/- {cv_recall.std() * 2:.4f})")
    print(f"  F1-Score:  {cv_f1.mean():.4f} (+/- {cv_f1.std() * 2:.4f})")
    print(f"  AUC:       {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")
    
    print(f"\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))
    
    # Store results in same format as train_delinquency_models
    model_results = {
        model_name: {
            'auc_score': auc_score,
            'accuracy': accuracy,
            'precision': precision,
            'recall': recall,
            'f1_score': f1,
            'cv_auc_mean': cv_scores.mean(),
            'cv_auc_std': cv_scores.std(),
            'cv_accuracy_mean': cv_accuracy.mean(),
            'cv_accuracy_std': cv_accuracy.std(),
            'cv_precision_mean': cv_precision.mean(),
            'cv_precision_std': cv_precision.std(),
            'cv_recall_mean': cv_recall.mean(),
            'cv_recall_std': cv_recall.std(),
            'cv_f1_mean': cv_f1.mean(),
            'cv_f1_std': cv_f1.std()
        }
    }
    
    return model, model_results, scaler, model_name
def analyze_feature_importance(model, feature_columns, model_name):
    """
    Analyze and display feature importance from the trained model.
    """
    print(f"\n{'='*60}")
    print(f"FEATURE IMPORTANCE ANALYSIS - {model_name}")
    print(f"{'='*60}")
    
    if hasattr(model, 'feature_importances_'):
        # Tree-based models
        importance_scores = model.feature_importances_
    elif hasattr(model, 'coef_'):
        # Linear models
        importance_scores = np.abs(model.coef_[0])
    else:
        print("Model does not support feature importance analysis")
        return None
    
    # Create feature importance DataFrame
    feature_importance_df = pd.DataFrame({
        'feature': feature_columns,
        'importance': importance_scores
    }).sort_values('importance', ascending=False)
    
    print("\nTop 20 Most Influential Features for Delinquency Prediction:")
    print("-" * 70)
    
    for i, (idx, row) in enumerate(feature_importance_df.head(20).iterrows()):
        print(f"{i+1:2d}. {row['feature']:<40} {row['importance']:.4f}")
    
    # Categorize features by table source
    user_features = [f for f in feature_importance_df['feature'] if any(
        prefix in f.lower() for prefix in ['age', 'income', 'employment', 'marital', 'province'])]
    loan_features = [f for f in feature_importance_df['feature'] if any(
        prefix in f.lower() for prefix in ['loan_', 'interest', 'ltv', 'balance', 'payment', 'debt_to'])]
    program_features = [f for f in feature_importance_df['feature'] if any(
        prefix in f.lower() for prefix in ['program_', 'difficulty', 'tuition', 'employment_rate', 'education'])]
    payment_features = [f for f in feature_importance_df['feature'] if any(
        prefix in f.lower() for prefix in ['missed', 'late', 'delinquency_rate', 'consistency'])]
    
    print(f"\nFeature Importance by Data Source:")
    print(f"\nUser Profile Features: {sum(feature_importance_df[feature_importance_df['feature'].isin(user_features)]['importance']):.3f}")
    print(f"\nLoan Info Features: {sum(feature_importance_df[feature_importance_df['feature'].isin(loan_features)]['importance']):.3f}")
    print(f"\nProgram Features: {sum(feature_importance_df[feature_importance_df['feature'].isin(program_features)]['importance']):.3f}")
    print(f"\nPayment Behavior Features: {sum(feature_importance_df[feature_importance_df['feature'].isin(payment_features)]['importance']):.3f}")
    
    return feature_importance_df

def calculate_risk_scores(model, X, scaler=None, model_name='', algorithm='random_forest'):
    """
    Calculate delinquency risk scores using ML classification algorithms: 0 (low), 1 (medium), 2 (high).
    
    Args:
        model: Trained ML model
        X: Feature matrix
        scaler: Feature scaler (for algorithms requiring scaling)
        model_name: Name of the model
        algorithm: Risk scoring algorithm ('random_forest', 'gradient_boosting', 'logistic_regression', 'svm', 'knn', 'neural_network')
    
    Returns:
        Array of risk scores (0, 1, or 2)
    """
    if model_name == 'Logistic Regression' and scaler is not None:
        X_scaled = scaler.transform(X)
        risk_probabilities = model.predict_proba(X_scaled)[:, 1]
    elif model_name == 'KNN':
        # Special handling for KNN to fix NumPy compatibility issues
        X_knn = np.ascontiguousarray(X.astype(np.float64)) if scaler is None else np.ascontiguousarray(scaler.transform(X).astype(np.float64))
        risk_probabilities = model.predict_proba(X_knn)[:, 1]
    else:
        risk_probabilities = model.predict_proba(X)[:, 1]
    
    print(f"\nUsing '{algorithm}' classification algorithm for risk scoring...")
    
    # Create training labels from probability distribution for classification algorithms
    prob_percentiles = np.percentile(risk_probabilities, [40, 80])  # 40-40-20 split
    training_labels = np.zeros(len(risk_probabilities))
    training_labels[risk_probabilities > prob_percentiles[0]] = 1
    training_labels[risk_probabilities > prob_percentiles[1]] = 2
    
    # Prepare data for classification
    if algorithm == 'knn':
        # Special handling for KNN to ensure proper array formatting
        X_for_classification = np.ascontiguousarray(X.astype(np.float64)) if scaler is None else np.ascontiguousarray(scaler.transform(X).astype(np.float64))
    else:
        X_for_classification = X if scaler is None else scaler.transform(X)
    
    if algorithm == 'random_forest':
        # Random Forest classification approach
        print("Training Random Forest classifier for risk level prediction...")
        from sklearn.ensemble import RandomForestClassifier
        
        rf_model = RandomForestClassifier(
            n_estimators=100, 
            max_depth=10, 
            random_state=42,
            class_weight='balanced',
            min_samples_split=5,
            min_samples_leaf=2
        )
        
        # Train-test split with stratification
        try:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        rf_model.fit(X_train, y_train)
        risk_scores = rf_model.predict(X_for_classification)
        
        print(f"Random Forest Training Accuracy: {rf_model.score(X_train, y_train):.3f}")
        print(f"Random Forest Test Accuracy: {rf_model.score(X_test, y_test):.3f}")
        
    elif algorithm == 'gradient_boosting':
        # Gradient Boosting classification approach
        print("Training Gradient Boosting classifier for risk level prediction...")
        from sklearn.ensemble import GradientBoostingClassifier
        
        gb_model = GradientBoostingClassifier(
            n_estimators=100,
            learning_rate=0.1,
            max_depth=6,
            random_state=42,
            min_samples_split=5,
            min_samples_leaf=2
        )
        
        try:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        gb_model.fit(X_train, y_train)
        risk_scores = gb_model.predict(X_for_classification)
        
        print(f"Gradient Boosting Training Accuracy: {gb_model.score(X_train, y_train):.3f}")
        print(f"Gradient Boosting Test Accuracy: {gb_model.score(X_test, y_test):.3f}")
        
    elif algorithm == 'logistic_regression':
        # Logistic Regression classification approach
        print("Training Logistic Regression classifier for risk level prediction...")
        from sklearn.linear_model import LogisticRegression
        
        lr_model = LogisticRegression(
            random_state=42,
            class_weight='balanced',
            max_iter=1000,
            C=1.0
        )
        
        try:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        lr_model.fit(X_train, y_train)
        risk_scores = lr_model.predict(X_for_classification)
        
        print(f"Logistic Regression Training Accuracy: {lr_model.score(X_train, y_train):.3f}")
        print(f"Logistic Regression Test Accuracy: {lr_model.score(X_test, y_test):.3f}")
        
    elif algorithm == 'neural_network':
        # Multi-layer Perceptron classification approach
        print("Training Neural Network classifier for risk level prediction...")
        from sklearn.neural_network import MLPClassifier
        
        nn_model = MLPClassifier(
            hidden_layer_sizes=(100, 50),
            activation='relu',
            solver='adam',
            alpha=0.001,
            learning_rate='adaptive',
            max_iter=500,
            random_state=42
        )
        
        try:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train, X_test, y_train, y_test = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        nn_model.fit(X_train, y_train)
        risk_scores = nn_model.predict(X_for_classification)
        
        print(f"Neural Network Training Accuracy: {nn_model.score(X_train, y_train):.3f}")
        print(f"Neural Network Test Accuracy: {nn_model.score(X_test, y_test):.3f}")
        
    elif algorithm == 'kmeans':
        # K-means clustering approach (unsupervised learning fallback)
        print("Using K-means clustering for risk level prediction...")
        from sklearn.cluster import KMeans
        kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
        clusters = kmeans.fit_predict(X_for_classification)
        
        # Map clusters to risk levels based on average probability in each cluster
        cluster_probs = []
        for i in range(3):
            cluster_mask = clusters == i
            if np.sum(cluster_mask) > 0:
                avg_prob = np.mean(risk_probabilities[cluster_mask])
                cluster_probs.append((i, avg_prob))
        
        # Sort clusters by average probability
        cluster_probs.sort(key=lambda x: x[1])
        
        risk_scores = np.zeros(len(risk_probabilities))
        for rank, (cluster_idx, _) in enumerate(cluster_probs):
            risk_scores[clusters == cluster_idx] = rank
            
        print(f"K-means cluster mapping: {[(f'Cluster {cp[0]}', f'Risk {rank}', f'Avg Prob {cp[1]:.3f}') for rank, cp in enumerate(cluster_probs)]}")
    
    elif algorithm == 'svm':
        # Enhanced SVM-based risk classification
        print("Training Support Vector Machine classifier for risk level prediction...")
        
        # Verify we have all three classes in training data
        unique_labels, label_counts = np.unique(training_labels, return_counts=True)
        print(f"Training label distribution: {dict(zip(unique_labels.astype(int), label_counts))}")
        
        # Enhanced SVM with optimized hyperparameters
        svm_model = SVC(
            kernel='rbf', 
            probability=True, 
            random_state=42,
            class_weight='balanced',
            C=10.0,  # Higher regularization for better generalization
            gamma='auto',
            decision_function_shape='ovr'
        )
        
        # Ensure sufficient samples for each class
        min_samples_per_class = 5
        for label in [0, 1, 2]:
            count = np.sum(training_labels == label)
            if count < min_samples_per_class:
                print(f"Warning: Only {count} samples for class {label}. Adjusting distribution...")
                prob_percentiles = np.percentile(risk_probabilities, [50, 85])
                training_labels = np.zeros(len(risk_probabilities))
                training_labels[risk_probabilities > prob_percentiles[0]] = 1
                training_labels[risk_probabilities > prob_percentiles[1]] = 2
                break
        
        try:
            X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        svm_model.fit(X_train_svm, y_train_svm)
        risk_scores = svm_model.predict(X_for_classification)
        
        print(f"SVM Training Accuracy: {svm_model.score(X_train_svm, y_train_svm):.3f}")
        print(f"SVM Test Accuracy: {svm_model.score(X_test_svm, y_test_svm):.3f}")
        
        # Enhanced post-processing for balanced distribution
        unique_output, output_counts = np.unique(risk_scores, return_counts=True)
        print(f"SVM Output distribution: {dict(zip(unique_output.astype(int), output_counts))}")
        
        if len(unique_output) < 3:
            print("SVM produced incomplete risk distribution. Applying intelligent post-processing...")
            # Get prediction probabilities for more nuanced classification
            svm_probs = svm_model.predict_proba(X_for_classification)
            
            # Use probability-based adjustment for missing classes
            prob_based_scores = np.argmax(svm_probs, axis=1)
            
            # Blend original predictions with probability-based ones
            final_scores = np.copy(risk_scores)
            
            # Fill missing medium risk category if needed
            if 1 not in risk_scores and len(np.where(prob_based_scores == 1)[0]) > 0:
                final_scores[prob_based_scores == 1] = 1
            
            risk_scores = final_scores
    
    elif algorithm == 'knn':
        # Enhanced KNN-based risk classification with improved training labels
        print("Training K-Nearest Neighbors classifier for risk level prediction...")
        
        # Create better balanced training labels using delinquency-informed approach
        # Use actual delinquency status to inform risk classification + probability spread
        
        # First, create base labels using probability terciles for balanced distribution
        prob_terciles = np.percentile(risk_probabilities, [33.33, 66.67])  # 33-33-34 split
        training_labels = np.zeros(len(risk_probabilities))
        training_labels[risk_probabilities > prob_terciles[0]] = 1  # Medium risk
        training_labels[risk_probabilities > prob_terciles[1]] = 2  # High risk
        
        # Then enhance with actual delinquency knowledge if available
        try:
            # Load actual delinquency status from the model's training data
            db_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'shared', 'student_loan_data.db'))
            import sqlite3
            conn = sqlite3.connect(db_path)
            cursor = conn.execute("SELECT payer_id, is_delinquent FROM user_profile ORDER BY payer_id")
            actual_delinquency = {row[0]: row[1] for row in cursor.fetchall()}
            conn.close()
            
            # Adjust labels based on actual delinquency status
            for i, prob in enumerate(risk_probabilities):
                payer_id = i + 1  # Assuming sequential payer IDs
                if payer_id in actual_delinquency:
                    is_delinquent = actual_delinquency[payer_id]
                    if is_delinquent and training_labels[i] == 0:  # Delinquent but labeled low risk
                        training_labels[i] = 1 if prob < 0.7 else 2  # Promote to medium or high
                    elif not is_delinquent and training_labels[i] == 2:  # Not delinquent but labeled high risk
                        training_labels[i] = 0 if prob < 0.3 else 1  # Demote to low or medium
        except Exception as e:
            print(f"Could not enhance with delinquency data: {e}")
            # Continue with probability-based labels only
        
        # Verify we have all three classes with sufficient samples
        unique_labels, label_counts = np.unique(training_labels, return_counts=True)
        print(f"Training label distribution: {dict(zip(unique_labels.astype(int), label_counts))}")
        
        # Ensure minimum samples per class (at least 10 samples per class)
        min_samples_per_class = 10
        for class_label in [0, 1, 2]:
            if class_label not in unique_labels or np.sum(training_labels == class_label) < min_samples_per_class:
                # Adjust percentiles to ensure balanced distribution
                if class_label == 0:  # Low risk
                    low_risk_indices = np.argsort(risk_probabilities)[:min_samples_per_class]
                    training_labels[low_risk_indices] = 0
                elif class_label == 2:  # High risk
                    high_risk_indices = np.argsort(risk_probabilities)[-min_samples_per_class:]
                    training_labels[high_risk_indices] = 2
                else:  # Medium risk
                    medium_indices = np.argsort(np.abs(risk_probabilities - np.median(risk_probabilities)))[:min_samples_per_class]
                    training_labels[medium_indices] = 1
        
        # Re-verify distribution
        unique_labels, label_counts = np.unique(training_labels, return_counts=True)
        print(f"Adjusted training label distribution: {dict(zip(unique_labels.astype(int), label_counts))}")
        
        # Optimize k value based on dataset size and ensure it works with 3 classes
        dataset_size = len(training_labels)
        if dataset_size < 100:
            optimal_k = 3
        elif dataset_size < 500:
            optimal_k = 5
        elif dataset_size < 1000:
            optimal_k = 7
        else:
            optimal_k = min(15, max(5, int(np.sqrt(dataset_size) * 0.5)))
        
        # Make sure k is compatible with smallest class size
        min_class_size = min(label_counts)
        optimal_k = min(optimal_k, min_class_size - 1)
        optimal_k = max(3, optimal_k)  # Minimum k of 3
        
        # Enhanced KNN with better parameters for 3-class classification
        knn_model = KNeighborsClassifier(
            n_neighbors=optimal_k, 
            weights='distance',
            algorithm='auto',
            metric='euclidean',
            p=2
        )
        
        try:
            X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42, 
                stratify=training_labels
            )
        except ValueError:
            X_train_knn, X_test_knn, y_train_knn, y_test_knn = train_test_split(
                X_for_classification, training_labels, test_size=0.3, random_state=42
            )
        
        # Ensure arrays are properly formatted and contiguous for KNN compatibility
        X_train_knn = np.ascontiguousarray(X_train_knn.astype(np.float64))
        X_test_knn = np.ascontiguousarray(X_test_knn.astype(np.float64))
        y_train_knn = np.ascontiguousarray(y_train_knn.astype(np.int32))
        X_for_classification_knn = np.ascontiguousarray(X_for_classification.astype(np.float64))
        
        knn_model.fit(X_train_knn, y_train_knn)
        risk_scores = knn_model.predict(X_for_classification_knn)
        
        print(f"KNN Training Accuracy (k={optimal_k}): {knn_model.score(X_train_knn, y_train_knn):.3f}")
        print(f"KNN Test Accuracy: {knn_model.score(X_test_knn, y_test_knn):.3f}")
        
        # Enhanced distribution checking and correction
        unique_output, output_counts = np.unique(risk_scores, return_counts=True)
        print(f"KNN Output distribution: {dict(zip(unique_output.astype(int), output_counts))}")
        
        # Only apply minimal adjustment if completely missing categories
        if len(unique_output) == 1:  # Only one category - this is a problem
            print("KNN produced only one risk category. Applying minimal diversity adjustment...")
            # Force small percentage to other categories based on extreme probabilities
            n_samples = len(risk_scores)
            n_high = max(1, n_samples // 50)  # At least 2% high risk
            n_medium = max(1, n_samples // 20)  # At least 5% medium risk
            
            # Find samples with highest probabilities for high risk
            high_risk_indices = np.argsort(risk_probabilities)[-n_high:]
            risk_scores[high_risk_indices] = 2
            
            # Find samples with medium probabilities for medium risk
            medium_prob_indices = np.argsort(np.abs(risk_probabilities - np.median(risk_probabilities)))[:n_medium]
            medium_prob_indices = medium_prob_indices[~np.isin(medium_prob_indices, high_risk_indices)]
            risk_scores[medium_prob_indices[:n_medium]] = 1
            
            final_unique, final_counts = np.unique(risk_scores, return_counts=True)
            print(f"Adjusted KNN distribution: {dict(zip(final_unique.astype(int), final_counts))}")
        else:
            print(f"KNN produced {len(unique_output)} risk categories - distribution looks reasonable.")
            
    elif algorithm == 'percentile':
        # Percentile-based risk classification using data-driven thresholds
        print("Using Percentile-based risk classification...")
        
        print(f"Raw probability distribution:")
        print(f"  Min: {np.min(risk_probabilities):.4f}")  
        print(f"  Max: {np.max(risk_probabilities):.4f}")
        print(f"  Mean: {np.mean(risk_probabilities):.4f}")
        print(f"  Std: {np.std(risk_probabilities):.4f}")
        
        # Sort probabilities to analyze distribution
        sorted_probs = np.sort(risk_probabilities)
        n_samples = len(risk_probabilities)
        
        print(f"  Total samples: {n_samples}")
        print(f"  Sample values at key positions:")
        print(f"    Position 600 (60%): {sorted_probs[599]:.4f}")  # 60% mark
        print(f"    Position 900 (90%): {sorted_probs[899]:.4f}")  # 90% mark
        
        # Calculate the actual threshold values using percentiles
        low_to_medium_threshold = np.percentile(risk_probabilities, 60)    # 60th percentile 
        medium_to_high_threshold = np.percentile(risk_probabilities, 90)   # 90th percentile
        
        print(f"Calculated thresholds:")
        print(f"  Low->Medium threshold (P60): {low_to_medium_threshold:.4f}")
        print(f"  Medium->High threshold (P90): {medium_to_high_threshold:.4f}")
        print(f"  Threshold difference: {medium_to_high_threshold - low_to_medium_threshold:.4f}")
        
        # Check if percentiles are too close (indicating low variance)
        threshold_diff = medium_to_high_threshold - low_to_medium_threshold
        prob_range = np.max(risk_probabilities) - np.min(risk_probabilities)
        
        if threshold_diff < 0.001 or threshold_diff < (prob_range * 0.02):
            print("WARNING: P60 and P90 are very close! Using adaptive quartile approach...")
            
            # Use quartiles when percentiles are too close
            q25 = np.percentile(risk_probabilities, 25)
            q50 = np.percentile(risk_probabilities, 50)  # median
            q75 = np.percentile(risk_probabilities, 75)
            
            print(f"Quartile thresholds: Q25={q25:.4f}, Q50={q50:.4f}, Q75={q75:.4f}")
            
            # Apply quartile-based classification
            risk_scores = np.zeros(len(risk_probabilities), dtype=int)
            risk_scores[risk_probabilities >= q50] = 1  # Medium risk (above median)
            risk_scores[risk_probabilities >= q75] = 2  # High risk (above 75th percentile)
            
            low_to_medium_threshold = q50
            medium_to_high_threshold = q75
            
        else:
            # Standard percentile-based approach
            risk_scores = np.zeros(len(risk_probabilities), dtype=int)
            risk_scores[risk_probabilities >= low_to_medium_threshold] = 1  # Medium risk
            risk_scores[risk_probabilities >= medium_to_high_threshold] = 2    # High risk
        
        # Count classifications for verification
        low_count = np.sum(risk_scores == 0)
        medium_count = np.sum(risk_scores == 1) 
        high_count = np.sum(risk_scores == 2)
        
        print(f"Classification results:")
        print(f"  Low risk: {low_count} ({low_count/n_samples*100:.1f}%)")
        print(f"  Medium risk: {medium_count} ({medium_count/n_samples*100:.1f}%)")
        print(f"  High risk: {high_count} ({high_count/n_samples*100:.1f}%)")
        print(f"  Applied thresholds: Low<{low_to_medium_threshold:.4f}, Medium<{medium_to_high_threshold:.4f}, High>={medium_to_high_threshold:.4f}")
        
        # Verify the distribution makes sense
        if medium_count == 0:
            print("ERROR: No Medium risk borrowers classified! This suggests algorithmic issue.")
        if low_count < n_samples * 0.2 or high_count < n_samples * 0.05:
            print(f"WARNING: Unusual distribution detected - check data variance")
            
    elif algorithm == 'threshold':
        # Fixed probability threshold-based risk classification  
        print("Using Fixed Threshold-based risk classification...")
        # Updated thresholds: <0.6=Low, 0.6-0.9=Medium, >0.9=High
        
        risk_scores = np.zeros(len(risk_probabilities))
        risk_scores[risk_probabilities >= 0.6] = 1  # Medium risk
        risk_scores[risk_probabilities > 0.9] = 2   # High risk
        
        print(f"Fixed thresholds: Low<0.6, Medium=0.6-0.9, High>0.9")
            
    else:
        raise ValueError(f"Unknown algorithm: {algorithm}. Choose from 'random_forest', 'gradient_boosting', 'logistic_regression', 'neural_network', 'svm', 'knn', 'kmeans', 'percentile', 'threshold'")
    
    # Convert to integers
    risk_scores = risk_scores.astype(int)
    
    # Distribution summary
    low_risk = np.sum(risk_scores == 0)
    medium_risk = np.sum(risk_scores == 1)
    high_risk = np.sum(risk_scores == 2)
    
    print(f"\nRisk Score Distribution Summary:")
    print(f"  Algorithm: {algorithm}")
    print(f"  Low Risk (0): {low_risk:,} borrowers ({low_risk/len(risk_scores)*100:.1f}%)")
    print(f"  Medium Risk (1): {medium_risk:,} borrowers ({medium_risk/len(risk_scores)*100:.1f}%)")
    print(f"  High Risk (2): {high_risk:,} borrowers ({high_risk/len(risk_scores)*100:.1f}%)")
    
    if algorithm == 'threshold':
        print(f"\nProbability Thresholds Used:")
        print(f"  Low -> Medium: 0.6")
        print(f"  Medium -> High: 0.9")
    elif algorithm == 'percentile':
        print(f"\nPercentile-based Classification Details:")
        print(f"  Target distribution: ~50% Low, ~25% Medium, ~25% High")
        print(f"  Method: {'Adaptive quartile thresholds' if 'q50' in locals() else 'Data-driven percentile thresholds'}")
        print(f"  Applied thresholds: P60/Q50={low_to_medium_threshold:.4f}, P90/Q75={medium_to_high_threshold:.4f}")
    elif algorithm in ['svm', 'knn']:
        print(f"\nML Classifier Details:")
        if algorithm == 'svm':
            print(f"  Kernel: RBF (Radial Basis Function)")
            print(f"  Training method: Stratified split with probability-based labels")
        else:
            print(f"  K-value: {optimal_k} (distance-weighted)")
            print(f"  Training method: Stratified split with probability-based labels")
    
    return risk_scores

def save_model_performance_report(model_results, output_dir=None, filename="model_performance.txt"):
    """
    Save detailed model performance metrics to a file.
    """
    import os
    from datetime import datetime
    
    # Use absolute path to ensure files are saved to the correct location
    if output_dir is None:
        output_dir = os.path.join(os.path.dirname(__file__), '..', 'risk_estimate_outputs')
    
    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)
    
    # Use fixed filename (file gets overwritten each session)
    filepath = os.path.join(output_dir, filename)
    
    with open(filepath, 'w') as f:
        f.write("DELINQUENCY ANALYSIS - MODEL PERFORMANCE REPORT\n")
        f.write("=" * 60 + "\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        
        f.write("SUMMARY TABLE\n")
        f.write("-" * 80 + "\n")
        f.write(f"{'Model':<20} {'Accuracy':<10} {'Precision':<11} {'Recall':<8} {'F1-Score':<9} {'AUC':<7}\n")
        f.write(f"{'-'*20} {'-'*10} {'-'*11} {'-'*8} {'-'*9} {'-'*7}\n")
        
        for name, results in model_results.items():
            accuracy = results.get('accuracy', 0.0)
            precision = results.get('precision', 0.0)
            recall = results.get('recall', 0.0)
            f1 = results.get('f1_score', 0.0)
            auc = results['auc_score']
            f.write(f"{name:<20} {accuracy:<10.4f} {precision:<11.4f} {recall:<8.4f} {f1:<9.4f} {auc:<7.4f}\n")
        
        f.write("\n\nDETAILED CROSS-VALIDATION RESULTS\n")
        f.write("-" * 80 + "\n")
        
        for name, results in model_results.items():
            f.write(f"\n{name.upper()}\n")
            f.write("-" * len(name) + "\n")
            
            # Test set performance
            f.write("Test Set Performance:\n")
            if 'accuracy' in results:
                f.write(f"  Accuracy:  {results['accuracy']:.4f}\n")
                f.write(f"  Precision: {results['precision']:.4f}\n")
                f.write(f"  Recall:    {results['recall']:.4f}\n")
                f.write(f"  F1-Score:  {results['f1_score']:.4f}\n")
            f.write(f"  AUC Score: {results['auc_score']:.4f}\n")
            
            # Cross-validation performance
            f.write("\nCross-Validation Performance (5-fold):\n")
            if 'cv_accuracy_mean' in results:
                f.write(f"  Accuracy:  {results['cv_accuracy_mean']:.4f} (+/- {results['cv_accuracy_std'] * 2:.4f})\n")
                f.write(f"  Precision: {results['cv_precision_mean']:.4f} (+/- {results['cv_precision_std'] * 2:.4f})\n")
                f.write(f"  Recall:    {results['cv_recall_mean']:.4f} (+/- {results['cv_recall_std'] * 2:.4f})\n")
                f.write(f"  F1-Score:  {results['cv_f1_mean']:.4f} (+/- {results['cv_f1_std'] * 2:.4f})\n")
                f.write(f"  AUC:       {results['cv_auc_mean']:.4f} (+/- {results['cv_auc_std'] * 2:.4f})\n")
            else:
                # Handle legacy format
                cv_mean = results.get('cv_mean', results.get('cv_auc_mean', 0.0))
                cv_std = results.get('cv_std', results.get('cv_auc_std', 0.0))
                f.write(f"  AUC:       {cv_mean:.4f} (+/- {cv_std * 2:.4f})\n")
    
    print(f"\nModel performance report saved to: {filepath}")
    return filepath

def update_loan_info_table(df, risk_scores, db_path=None):
    """
    Add delinquency_risk column to loan_info table and update with calculated scores using centralized database methods.
    """
    db_manager = DatabaseManager(db_path) if db_path else DatabaseManager()
    
    # Create a dictionary mapping payer_id to risk_score
    risk_score_dict = {}
    for payer_id, risk_score in zip(df['payer_id'], risk_scores):
        risk_score_dict[str(payer_id)] = int(risk_score)
    
    # Add the delinquency_risk column if it doesn't exist
    try:
        conn = db_manager.get_connection()
        cursor = conn.cursor()
        cursor.execute("ALTER TABLE loan_info ADD COLUMN delinquency_risk INTEGER")
        conn.commit()
        conn.close()
        print("Added delinquency_risk column to loan_info table")
    except Exception as e:
        if "duplicate column name" in str(e).lower():
            print("delinquency_risk column already exists")
        else:
            print(f"Error adding column: {e}")
    
    # Update risk scores using centralized batch update method
    try:
        rows_updated = db_manager.batch_update_delinquency_risks(risk_score_dict)
        print(f"Updated {rows_updated} risk scores in loan_info table")
        
        # Show statistics
        print(f"Risk score statistics:")
        print(f"  Low Risk (0): {np.sum(risk_scores == 0):,} borrowers")
        print(f"  Medium Risk (1): {np.sum(risk_scores == 1):,} borrowers")
        print(f"  High Risk (2): {np.sum(risk_scores == 2):,} borrowers")
        
    except Exception as e:
        print(f"Error updating risk scores: {e}")
        raise

def generate_analysis_report(df, feature_importance_df, model_results, risk_scores):
    """
    Generate comprehensive delinquency analysis report.
    """
    print(f"\n{'='*80}")
    print(f"COMPREHENSIVE DELINQUENCY ANALYSIS REPORT")
    print(f"{'='*80}")
    
    print(f"\nDataset Overview:")
    print(f"- Total borrowers analyzed: {len(df):,}")
    print(f"- Delinquent borrowers: {df['is_delinquent'].sum():,}")
    print(f"- Overall delinquency rate: {df['is_delinquent'].mean():.2%}")
    
    print(f"\nModel Performance Summary:")
    print(f"{'Model':<20} {'Accuracy':<10} {'Precision':<11} {'Recall':<8} {'F1-Score':<9} {'AUC':<7}")
    print(f"{'-'*20} {'-'*10} {'-'*11} {'-'*8} {'-'*9} {'-'*7}")
    for name, results in model_results.items():
        accuracy = results.get('accuracy', 0.0)
        precision = results.get('precision', 0.0)
        recall = results.get('recall', 0.0)
        f1 = results.get('f1_score', 0.0)
        auc = results['auc_score']
        print(f"{name:<20} {accuracy:<10.4f} {precision:<11.4f} {recall:<8.4f} {f1:<9.4f} {auc:<7.4f}")
    
    print(f"\nTop 10 Risk Factors for Delinquency:")
    for i, (_, row) in enumerate(feature_importance_df.head(10).iterrows()):
        print(f"{i+1:2d}. {row['feature']}")
    
    # Risk score distribution with discrete levels
    risk_labels = {0: 'Low Risk', 1: 'Medium Risk', 2: 'High Risk'}
    
    # Create risk categories based on the actual risk scores
    df_with_risk = df.copy()
    df_with_risk['calculated_risk'] = risk_scores
    df_with_risk['risk_category'] = df_with_risk['calculated_risk'].map(risk_labels)
    
    print(f"\nRisk Score Distribution:")
    for risk_level in [0, 1, 2]:
        count = np.sum(risk_scores == risk_level)
        pct = count / len(risk_scores) * 100
        print(f"- {risk_labels[risk_level]} ({risk_level}): {count:,} borrowers ({pct:.1f}%)")
    
    # Correlation with actual delinquency - improved analysis
    print(f"\nRisk Score Validation (Actual Delinquency Rates by Risk Level):")
    total_borrowers = len(df_with_risk)
    for risk_level in [0, 1, 2]:
        level_data = df_with_risk[df_with_risk['calculated_risk'] == risk_level]
        if len(level_data) > 0:
            actual_delinq_rate = level_data['is_delinquent'].mean()
            borrowers_count = len(level_data)
            borrowers_pct = (borrowers_count / total_borrowers) * 100
            print(f"- {risk_labels[risk_level]} ({risk_level}):")
            print(f"    Actual Delinquency Rate: {actual_delinq_rate:.1%}")
            print(f"    Borrowers in Level: {borrowers_count:,} ({borrowers_pct:.1f}% of total)")
    
    # Show examples by risk level
    for risk_level in [2, 1, 0]:  # Start with highest risk
        level_data = df_with_risk[df_with_risk['calculated_risk'] == risk_level]
        if len(level_data) > 0:
            sample_size = min(5, len(level_data))
            samples = level_data.sample(n=sample_size, random_state=42)[['payer_id', 'calculated_risk', 'is_delinquent']]
            print(f"\n{sample_size} Sample {risk_labels[risk_level]} Borrowers:")
            for _, row in samples.iterrows():
                status = "DELINQUENT" if row['is_delinquent'] else "Current"
                print(f"  Payer {row['payer_id']}: Risk Level {int(row['calculated_risk'])} - {status}")

def parse_arguments():
    """
    Parse command line arguments for delinquency analysis.
    """
    parser = argparse.ArgumentParser(
        description="Comprehensive Delinquency Risk Analysis with Discrete Risk Scores",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Risk Scoring Algorithms:
  percentile  - Bottom 60% = Low(0), Next 30% = Medium(1), Top 10% = High(2)
  threshold   - Fixed probability thresholds: <0.6=Low, 0.6-0.9=Medium, >0.9=High
  kmeans      - K-means clustering of probabilities into 3 risk groups
  svm         - Support Vector Machine classifier trained on probability-based risk labels
  knn         - K-Nearest Neighbors classifier with optimal k and distance weighting

Examples:
  python delinquency_analysis.py --algorithm percentile
  python delinquency_analysis.py --algorithm svm
  python delinquency_analysis.py --algorithm knn
  
Database connection is handled automatically through the centralized DatabaseManager.
        """
    )
    
    parser.add_argument(
        "--algorithm",
        choices=['random_forest', 'gradient_boosting', 'logistic_regression', 'neural_network', 'svm', 'knn', 'kmeans'],
        default='random_forest',
        help="Risk scoring algorithm to use (default: random_forest)"
    )
    
    parser.add_argument(
        "--db_path", 
        default="student_loan_data.db",
        help="Path to the SQLite database file (default: student_loan_data.db)"
    )
    
    return parser.parse_args()

def main():
    """
    Main execution function for delinquency analysis.
    """
    # Initialize session logging
    logger = init_session_logging()
    
    try:
        args = parse_arguments()
        
        print("Starting Comprehensive Delinquency Risk Analysis...")
        print("=" * 60)
        print(f"Algorithm: {args.algorithm}")
        print(f"Database: {args.db_path}")
        print(f"Risk Levels: 0 (Low), 1 (Medium), 2 (High)")
        print("=" * 60)
        
        # Load and prepare data using centralized database methods
        df = load_comprehensive_dataset(db_path=args.db_path)
        df = engineer_features(df)
        X, y, feature_columns, label_encoders = prepare_ml_features(df)
        
        # Train models
        best_model, model_results, scaler = train_delinquency_models(X, y)
        
        # Analyze feature importance
        best_model_name = max(model_results.keys(), key=lambda x: model_results[x]['auc_score'])
        feature_importance_df = analyze_feature_importance(best_model, feature_columns, best_model_name)
        
        # Save detailed performance report
        save_model_performance_report(model_results)
        
        # Calculate risk scores using specified algorithm
        risk_scores = calculate_risk_scores(best_model, X, scaler, best_model_name, args.algorithm)
        
        # Update database using centralized methods  
        update_loan_info_table(df, risk_scores, db_path=args.db_path)
        
        # Generate report
        generate_analysis_report(df, feature_importance_df, model_results, risk_scores)
        
        # Display best model summary
        print(f"\n{'='*80}")
        print(f"BEST MODEL SUMMARY")
        print(f"{'='*80}")
        best_results = model_results[best_model_name]
        print(f"Best Performing Model: {best_model_name}")
        if 'accuracy' in best_results:
            print(f"  Test Accuracy:     {best_results['accuracy']:.4f}")
            print(f"  Test Precision:    {best_results['precision']:.4f}")
            print(f"  Test Recall:       {best_results['recall']:.4f}")
            print(f"  Test F1-Score:     {best_results['f1_score']:.4f}")
        print(f"  Test AUC Score:    {best_results['auc_score']:.4f}")
        if 'cv_accuracy_mean' in best_results:
            print(f"  CV Accuracy:       {best_results['cv_accuracy_mean']:.4f} (+/- {best_results['cv_accuracy_std'] * 2:.4f})")
            print(f"  CV AUC:            {best_results['cv_auc_mean']:.4f} (+/- {best_results['cv_auc_std'] * 2:.4f})")
        else:
            cv_mean = best_results.get('cv_mean', best_results.get('cv_auc_mean', 0.0))
            cv_std = best_results.get('cv_std', best_results.get('cv_auc_std', 0.0))
            print(f"  CV AUC:            {cv_mean:.4f} (+/- {cv_std * 2:.4f})")
        
        print(f"\nDelinquency analysis complete!")
        print(f"The loan_info table has been updated with delinquency_risk scores.")
        print(f"Risk scores: 0 (Low Risk), 1 (Medium Risk), 2 (High Risk)")
        print(f"Algorithm used: {args.algorithm}")
        print(f"Performance report saved in risk_estimate_outputs/ directory")
        
    finally:
        # Finalize session logging and create output files
        md_file, html_file, txt_file = finalize_session_logging()
        if md_file and html_file:
            print(f"\nSession logs saved to:")
            print(f"  Markdown: {os.path.basename(md_file)}")
            print(f"  HTML: {os.path.basename(html_file)}")
            print(f"  Text: {os.path.basename(txt_file)}")
            print(f"  Location: {os.path.dirname(md_file)}")
        
        print(f"\nRisk estimation session completed successfully!")

if __name__ == "__main__":
    main()